### ISSUE TITLE
Cannot clone 

### ISSUE THREAD

**Issue by sambsp** [ErfanMo77/Syndra#71]
E:\>git clone --recursive https://github.com/ErfanMo77/Syndra-Engine
Cloning into 'Syndra-Engine'...
remote: Enumerating objects: 3632, done.
remote: Counting objects: 100% (859/859), done.
remote: Compressing objects: 100% (563/563), done.
remote: Total 3632 (delta 513), reused 560 (delta 295), pack-reused 2773
Receiving objects: 100% (3632/3632), 247.34 MiB | 17.46 MiB/s, done.
Resolving deltas: 100% (2081/2081), done.
Updating files: 100% (331/331), done.
Submodule 'Syndra/vendor/GLFW' (https://github.com/ErfanMo77/glfw.git) registered for path 'Syndra/vendor/GLFW'
Submodule 'Syndra/vendor/ImGuizmo' (https://github.com/ErfanMo77/ImGuizmo.git) registered for path 'Syndra/vendor/ImGuizmo'
Submodule 'Syndra/vendor/glm' (https://github.com/g-truc/glm.git) registered for path 'Syndra/vendor/glm'
Submodule 'Syndra/vendor/imgui' (https://github.com/ErfanMo77/imgui.git) registered for path 'Syndra/vendor/imgui'
Submodule 'Syndra/vendor/spdlog' (https://github.com/gabime/spdlog.git) registered for path 'Syndra/vendor/spdlog'
Submodule 'Syndra/vendor/yaml-cpp' (https://github.com/ErfanMo77/yaml-cpp.git) registered for path 'Syndra/vendor/yaml-cpp'
Cloning into 'E:/Syndra-Engine/Syndra/vendor/GLFW'...
remote: Enumerating objects: 26645, done.
remote: Total 26645 (delta 0), reused 0 (delta 0), pack-reused 26645
Receiving objects: 100% (26645/26645), 13.01 MiB | 8.51 MiB/s, done.
Resolving deltas: 100% (18788/18788), done.
Cloning into 'E:/Syndra-Engine/Syndra/vendor/ImGuizmo'...
remote: Enumerating objects: 727, done.
remote: Counting objects: 100% (4/4), done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 727 (delta 0), reused 1 (delta 0), pack-reused 723
Receiving objects: 100% (727/727), 3.28 MiB | 9.77 MiB/s, done.
Resolving deltas: 100% (419/419), done.
Cloning into 'E:/Syndra-Engine/Syndra/vendor/glm'...
remote: Enumerating objects: 56574, done.
remote: Counting objects: 100% (290/290), done.
remote: Compressing objects: 100% (172/172), done.
remote: Total 56574 (delta 172), reused 193 (delta 118), pack-reused 56284
Receiving objects: 100% (56574/56574), 69.13 MiB | 12.39 MiB/s, done.
Resolving deltas: 100% (42684/42684), done.
Cloning into 'E:/Syndra-Engine/Syndra/vendor/imgui'...
remote: Enumerating objects: 37906, done.
remote: Total 37906 (delta 0), reused 0 (delta 0), pack-reused 37906
Receiving objects: 100% (37906/37906), 64.29 MiB | 17.02 MiB/s, done.
Resolving deltas: 100% (28512/28512), done.
Cloning into 'E:/Syndra-Engine/Syndra/vendor/spdlog'...
remote: Enumerating objects: 23950, done.
remote: Counting objects: 100% (20/20), done.
remote: Compressing objects: 100% (10/10), done.
remote: Total 23950 (delta 7), reused 19 (delta 7), pack-reused 23930
Receiving objects: 100% (23950/23950), 40.10 MiB | 8.39 MiB/s, done.
Resolving deltas: 100% (15851/15851), done.
Cloning into 'E:/Syndra-Engine/Syndra/vendor/yaml-cpp'...
remote: Enumerating objects: 8150, done.
remote: Counting objects: 100% (15/15), done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 8150 (delta 7), reused 12 (delta 7), pack-reused 8135
Receiving objects: 100% (8150/8150), 3.87 MiB | 4.58 MiB/s, done.
Resolving deltas: 100% (5314/5314), done.
Submodule path 'Syndra/vendor/GLFW': checked out 'f9c9ff772231aa103c21c80e25971b9acb715f3c'
fatal: remote error: upload-pack: not our ref 7ce7a1ffff903ea8cf0aa8b281b583427ab9d182
Fetched in submodule path 'Syndra/vendor/ImGuizmo', but it did not contain 7ce7a1ffff903ea8cf0aa8b281b583427ab9d182. Direct fetching of that commit failed.

**Comment by ErfanMo77** [comment]
At the moment `git clone --recursive` doesn't work because there is a problem with ImGuizmo submodule. However, you can clone the repo non-recursively and then use `git submodule update --init` to add the submodules.

Thank you!

**Comment by sambsp** [comment]
@ErfanMo77

Used method from your comment, it works. Thanks.
