### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by sambsp** [ErfanMo77/Syndra#72]
ErfanMo77,

Thanks for your great project. I met building fail, 

used Visual Studio version: 16.11.8, Community 2019

the error list snapshot:

![image](https://user-images.githubusercontent.com/4620696/147804028-d48e217f-9483-4e97-ab14-caff68378f50.png)

the log from Visual Studio 2019:

Build started...
1>------ Build started: Project: GLFW, Configuration: Debug x64 ------
2>------ Build started: Project: Glad, Configuration: Debug x64 ------
3>------ Build started: Project: imgui, Configuration: Debug x64 ------
4>------ Build started: Project: yaml-cpp, Configuration: Debug x64 ------
1>GLFW.vcxproj -> E:\Syndra\bin\Debug-windows-x86_64\GLFW\GLFW.lib
2>glad.c
3>imgui.vcxproj -> E:\Syndra\bin\Debug-windows-x86_64\imgui\imgui.lib
4>yaml-cpp.vcxproj -> E:\Syndra\bin\Debug-windows-x86_64\yaml-cpp\yaml-cpp.lib
2>Glad.vcxproj -> E:\Syndra\bin\Debug-windows-x86_64\Glad\Glad.lib
5>------ Build started: Project: Syndra, Configuration: Debug x64 ------
5>lpch.cpp
5>Application.cpp
5>Layer.cpp
5>LayerStack.cpp
5>Log.cpp
5>Window.cpp
5>ImGuiBuild.cpp
5>ImGuiLayer.cpp
5>Buffer.cpp
5>Environment.cpp
5>E:\Syndra\Syndra\src\Engine\Renderer\Environment.cpp(159,26): warning C4244: 'initializing': conversion from 'double' to 'unsigned int', possible loss of data
5>E:\Syndra\Syndra\src\Engine\Renderer\Environment.cpp(160,27): warning C4244: 'initializing': conversion from 'double' to 'unsigned int', possible loss of data
5>FrameBuffer.cpp
5>LightManager.cpp
5>Material.cpp
5>Mesh.cpp
5>E:\Syndra\Syndra\src\Engine\Renderer\Mesh.cpp(18,95): warning C4267: 'argument': conversion from 'size_t' to 'uint32_t', possible loss of data
5>E:\Syndra\Syndra\src\Engine\Renderer\Mesh.cpp(19,66): warning C4267: 'argument': conversion from 'size_t' to 'uint32_t', possible loss of data
5>Model.cpp
5>OrthographicCamera.cpp
5>PerspectiveCamera.cpp
5>E:\Syndra\Syndra\src\Engine\Renderer\PerspectiveCamera.cpp(121,31): warning C4244: '=': conversion from 'unsigned int' to 'float', possible loss of data
5>E:\Syndra\Syndra\src\Engine\Renderer\PerspectiveCamera.cpp(122,33): warning C4244: '=': conversion from 'unsigned int' to 'float', possible loss of data
5>RenderCommand.cpp
5>RenderPass.cpp
5>Renderer.cpp
5>RendererAPI.cpp
5>Generating Code...
5>Compiling...
5>SceneRenderer.cpp
5>E:\Syndra\Syndra\src\Engine\Renderer\SceneRenderer.cpp(39,51): warning C4267: 'argument': conversion from 'size_t' to 'uint32_t', possible loss of data
5>E:\Syndra\Syndra\src\Engine\Renderer\SceneRenderer.cpp(331,61): warning C4244: 'argument': conversion from 'float' to 'int', possible loss of data
5>E:\Syndra\Syndra\src\Engine\Renderer\SceneRenderer.cpp(332,71): warning C4244: 'argument': conversion from 'float' to 'int', possible loss of data
5>E:\Syndra\Syndra\src\Engine\Renderer\SceneRenderer.cpp(430,73): warning C4312: 'type cast': conversion from 'uint32_t' to 'ImTextureID' of greater size
5>E:\Syndra\Syndra\src\Engine\Renderer\SceneRenderer.cpp(438,73): warning C4312: 'type cast': conversion from 'uint32_t' to 'ImTextureID' of greater size
5>E:\Syndra\Syndra\src\Engine\Renderer\SceneRenderer.cpp(446,73): warning C4312: 'type cast': conversion from 'uint32_t' to 'ImTextureID' of greater size
5>E:\Syndra\Syndra\src\Engine\Renderer\SceneRenderer.cpp(454,73): warning C4312: 'type cast': conversion from 'uint32_t' to 'ImTextureID' of greater size
5>E:\Syndra\Syndra\src\Engine\Renderer\SceneRenderer.cpp(538,75): warning C4312: 'type cast': conversion from 'uint32_t' to 'ImTextureID' of greater size
5>Shader.cpp
5>Texture.cpp
5>UniformBuffer.cpp
5>VertexArray.cpp
5>Components.cpp
5>Entity.cpp
5>Light.cpp
5>Scene.cpp
5>E:\Syndra\Syndra\src\Engine\Scene\Scene.cpp(155,36): warning C4244: 'argument': conversion from 'uint32_t' to 'float', possible loss of data
5>E:\Syndra\Syndra\src\Engine\Scene\Scene.cpp(155,29): warning C4244: 'argument': conversion from 'uint32_t' to 'float', possible loss of data
5>SceneCamera.cpp
5>SceneSerializer.cpp
5>E:\Syndra\Syndra\vendor\spdlog\include\spdlog\fmt\bundled\format.h(3510,29): error C2668: 'fmt::v7::make_format_args': ambiguous call to overloaded function
5>E:\Syndra\Syndra\vendor\spdlog\include\spdlog\fmt\bundled\core.h(1424,43): message : could be 'fmt::v7::format_arg_store<context,std::string> fmt::v7::make_format_args<context,std::string>(const std::string &)'
5>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\format(2849,17): message : or       'auto std::make_format_args<context,std::string>(const std::string &)' [found using argument-dependent lookup]
5>E:\Syndra\Syndra\vendor\spdlog\include\spdlog\fmt\bundled\format.h(3506,1): message : while trying to match the argument list '(std::string)'
5>E:\Syndra\Syndra\vendor\spdlog\include\spdlog\logger.h(330): message : see reference to function template instantiation 'std::back_insert_iterator<fmt::v7::detail::buffer<char>> fmt::v7::format_to<FormatString,std::string&,250,char>(fmt::v7::basic_memory_buffer<char,250,std::allocator<char>> &,const S &,std::string &)' being compiled
5>        with
5>        [
5>            FormatString=spdlog::string_view_t,
5>            S=spdlog::string_view_t
5>        ]
5>E:\Syndra\Syndra\vendor\spdlog\include\spdlog\logger.h(86): message : see reference to function template instantiation 'void spdlog::logger::log_<spdlog::string_view_t,std::string&>(spdlog::source_loc,spdlog::level::level_enum,const FormatString &,std::string &)' being compiled
5>        with
5>        [
5>            FormatString=spdlog::string_view_t
5>        ]
5>E:\Syndra\Syndra\vendor\spdlog\include\spdlog\logger.h(92): message : see reference to function template instantiation 'void spdlog::logger::log<std::string&>(spdlog::source_loc,spdlog::level::level_enum,spdlog::string_view_t,std::string &)' being compiled
5>E:\Syndra\Syndra\vendor\spdlog\include\spdlog\logger.h(98): message : see reference to function template instantiation 'void spdlog::logger::log<char[26],std::string&>(spdlog::level::level_enum,const FormatString (&),std::string &)' being compiled
5>        with
5>        [
5>            FormatString=char [26]
5>        ]
5>E:\Syndra\Syndra\src\Engine\Scene\SceneSerializer.cpp(289): message : see reference to function template instantiation 'void spdlog::logger::trace<char[26],std::string&>(const FormatString (&),std::string &)' being compiled
5>        with
5>        [
5>            FormatString=char [26]
5>        ]
5>E:\Syndra\Syndra\vendor\spdlog\include\spdlog\fmt\bundled\format.h(3509,18): error C2672: 'fmt::v7::detail::vformat_to': no matching overloaded function found
5>E:\Syndra\Syndra\vendor\spdlog\include\spdlog\fmt\bundled\format.h(3506,1): error C2780: 'basic_format_context<std::back_insert_iterator<fmt::v7::detail::buffer<T>>,Char>::iterator fmt::v7::detail::vformat_to(fmt::v7::detail::buffer<T> &,fmt::v7::basic_string_view<Char>,fmt::v7::basic_format_args<fmt::v7::basic_format_context<std::back_insert_iterator<fmt::v7::detail::buffer<type_identity<T>::type>>,type_identity<T>::type>>)': expects 3 arguments - 2 provided
5>E:\Syndra\Syndra\vendor\spdlog\include\spdlog\fmt\bundled\core.h(1775): message : see declaration of 'fmt::v7::detail::vformat_to'
5>Math.cpp
5>E:\Syndra\Syndra\src\Engine\Utils\Math.cpp(37,16): warning C4101: 'Pdum3': unreferenced local variable
5>OpenGLBuffer.cpp
5>OpenGLContext.cpp
5>OpenGLFrameBuffer.cpp
5>E:\Syndra\Syndra\src\Platform\OpenGL\OpenGLFrameBuffer.cpp(129,72): warning C4267: 'argument': conversion from 'size_t' to 'GLsizei', possible loss of data
5>E:\Syndra\Syndra\src\Platform\OpenGL\OpenGLFrameBuffer.cpp(138,73): warning C4267: 'argument': conversion from 'size_t' to 'GLsizei', possible loss of data
5>E:\Syndra\Syndra\src\Platform\OpenGL\OpenGLFrameBuffer.cpp(153,84): warning C4267: 'argument': conversion from 'size_t' to 'uint32_t', possible loss of data
5>E:\Syndra\Syndra\src\Platform\OpenGL\OpenGLFrameBuffer.cpp(161,140): warning C4267: 'argument': conversion from 'size_t' to 'int', possible loss of data
5>E:\Syndra\Syndra\src\Platform\OpenGL\OpenGLFrameBuffer.cpp(164,141): warning C4267: 'argument': conversion from 'size_t' to 'int', possible loss of data
5>E:\Syndra\Syndra\src\Platform\OpenGL\OpenGLFrameBuffer.cpp(167,146): warning C4267: 'argument': conversion from 'size_t' to 'int', possible loss of data
5>E:\Syndra\Syndra\src\Platform\OpenGL\OpenGLFrameBuffer.cpp(208,52): warning C4267: 'argument': conversion from 'size_t' to 'GLsizei', possible loss of data
5>OpenGLRendererAPI.cpp
5>OpenGLShader.cpp
5>E:\Syndra\Syndra\src\Platform\OpenGL\OpenGLShader.cpp(262,71): warning C4267: 'initializing': conversion from 'size_t' to 'uint32_t', possible loss of data
5>E:\Syndra\Syndra\src\Platform\OpenGL\OpenGLShader.cpp(264,52): warning C4267: 'initializing': conversion from 'size_t' to 'int', possible loss of data
5>E:\Syndra\Syndra\src\Platform\OpenGL\OpenGLShader.cpp(299,71): warning C4267: 'initializing': conversion from 'size_t' to 'uint32_t', possible loss of data
5>E:\Syndra\Syndra\src\Platform\OpenGL\OpenGLShader.cpp(301,52): warning C4267: 'initializing': conversion from 'size_t' to 'int', possible loss of data
5>E:\Syndra\Syndra\vendor\spdlog\include\spdlog\fmt\bundled\format.h(3510,29): error C2668: 'fmt::v7::make_format_args': ambiguous call to overloaded function
5>E:\Syndra\Syndra\vendor\spdlog\include\spdlog\fmt\bundled\core.h(1424,43): message : could be 'fmt::v7::format_arg_store<context,std::string> fmt::v7::make_format_args<context,std::string>(const std::string &)'
5>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\format(2849,17): message : or       'auto std::make_format_args<context,std::string>(const std::string &)' [found using argument-dependent lookup]
5>E:\Syndra\Syndra\vendor\spdlog\include\spdlog\fmt\bundled\format.h(3506,1): message : while trying to match the argument list '(const std::string)'
5>E:\Syndra\Syndra\vendor\spdlog\include\spdlog\logger.h(330): message : see reference to function template instantiation 'std::back_insert_iterator<fmt::v7::detail::buffer<char>> fmt::v7::format_to<FormatString,const std::string&,250,char>(fmt::v7::basic_memory_buffer<char,250,std::allocator<char>> &,const S &,const std::string &)' being compiled
5>        with
5>        [
5>            FormatString=spdlog::string_view_t,
5>            S=spdlog::string_view_t
5>        ]
5>E:\Syndra\Syndra\vendor\spdlog\include\spdlog\logger.h(86): message : see reference to function template instantiation 'void spdlog::logger::log_<spdlog::string_view_t,const std::string&>(spdlog::source_loc,spdlog::level::level_enum,const FormatString &,const std::string &)' being compiled
5>        with
5>        [
5>            FormatString=spdlog::string_view_t
5>        ]
5>E:\Syndra\Syndra\vendor\spdlog\include\spdlog\logger.h(92): message : see reference to function template instantiation 'void spdlog::logger::log<const std::string&>(spdlog::source_loc,spdlog::level::level_enum,spdlog::string_view_t,const std::string &)' being compiled
5>E:\Syndra\Syndra\vendor\spdlog\include\spdlog\logger.h(122): message : see reference to function template instantiation 'void spdlog::logger::log<char[31],const std::string&>(spdlog::level::level_enum,const FormatString (&),const std::string &)' being compiled
5>        with
5>        [
5>            FormatString=char [31]
5>        ]
5>E:\Syndra\Syndra\src\Platform\OpenGL\OpenGLShader.cpp(132): message : see reference to function template instantiation 'void spdlog::logger::error<char[31],const std::string&>(const FormatString (&),const std::string &)' being compiled
5>        with
5>        [
5>            FormatString=char [31]
5>        ]
5>E:\Syndra\Syndra\vendor\spdlog\include\spdlog\fmt\bundled\format.h(3509,18): error C2672: 'fmt::v7::detail::vformat_to': no matching overloaded function found
5>E:\Syndra\Syndra\vendor\spdlog\include\spdlog\fmt\bundled\format.h(3506,1): error C2780: 'basic_format_context<std::back_insert_iterator<fmt::v7::detail::buffer<T>>,Char>::iterator fmt::v7::detail::vformat_to(fmt::v7::detail::buffer<T> &,fmt::v7::basic_string_view<Char>,fmt::v7::basic_format_args<fmt::v7::basic_format_context<std::back_insert_iterator<fmt::v7::detail::buffer<type_identity<T>::type>>,type_identity<T>::type>>)': expects 3 arguments - 2 provided
5>E:\Syndra\Syndra\vendor\spdlog\include\spdlog\fmt\bundled\core.h(1775): message : see declaration of 'fmt::v7::detail::vformat_to'
5>OpenGLTexture1D.cpp
5>OpenGLTexture2D.cpp
5>OpenGLUniformBuffer.cpp
5>Generating Code...
5>Compiling...
5>OpenGLVertexArray.cpp
5>WindowsInput.cpp
5>WindowsUtils.cpp
5>WindowsWindow.cpp
5>E:\Syndra\Syndra\vendor\spdlog\include\spdlog\fmt\bundled\format.h(3510,29): error C2668: 'fmt::v7::make_format_args': ambiguous call to overloaded function
5>E:\Syndra\Syndra\vendor\spdlog\include\spdlog\fmt\bundled\core.h(1424,43): message : could be 'fmt::v7::format_arg_store<context,std::string,uint32_t,uint32_t> fmt::v7::make_format_args<context,std::string,uint32_t,uint32_t>(const std::string &,const uint32_t &,const uint32_t &)'
5>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\format(2849,17): message : or       'auto std::make_format_args<context,std::string,uint32_t,uint32_t>(const std::string &,const uint32_t &,const uint32_t &)' [found using argument-dependent lookup]
5>E:\Syndra\Syndra\vendor\spdlog\include\spdlog\fmt\bundled\format.h(3506,1): message : while trying to match the argument list '(const std::string, const uint32_t, const uint32_t)'
5>E:\Syndra\Syndra\vendor\spdlog\include\spdlog\logger.h(330): message : see reference to function template instantiation 'std::back_insert_iterator<fmt::v7::detail::buffer<char>> fmt::v7::format_to<FormatString,const std::string&,const uint32_t&,const uint32_t&,250,char>(fmt::v7::basic_memory_buffer<char,250,std::allocator<char>> &,const S &,const std::string &,const uint32_t &,const uint32_t &)' being compiled
5>        with
5>        [
5>            FormatString=spdlog::string_view_t,
5>            S=spdlog::string_view_t
5>        ]
5>E:\Syndra\Syndra\vendor\spdlog\include\spdlog\logger.h(86): message : see reference to function template instantiation 'void spdlog::logger::log_<spdlog::string_view_t,const std::string&,const uint32_t&,const uint32_t&>(spdlog::source_loc,spdlog::level::level_enum,const FormatString &,const std::string &,const uint32_t &,const uint32_t &)' being compiled
5>        with
5>        [
5>            FormatString=spdlog::string_view_t
5>        ]
5>E:\Syndra\Syndra\vendor\spdlog\include\spdlog\logger.h(92): message : see reference to function template instantiation 'void spdlog::logger::log<const std::string&,const uint32_t&,const uint32_t&>(spdlog::source_loc,spdlog::level::level_enum,spdlog::string_view_t,const std::string &,const uint32_t &,const uint32_t &)' being compiled
5>E:\Syndra\Syndra\vendor\spdlog\include\spdlog\logger.h(110): message : see reference to function template instantiation 'void spdlog::logger::log<char[31],const std::string&,const uint32_t&,const uint32_t&>(spdlog::level::level_enum,const FormatString (&),const std::string &,const uint32_t &,const uint32_t &)' being compiled
5>        with
5>        [
5>            FormatString=char [31]
5>        ]
5>E:\Syndra\Syndra\src\Platform\Windows\WindowsWindow.cpp(47): message : see reference to function template instantiation 'void spdlog::logger::info<char[31],const std::string&,const uint32_t&,const uint32_t&>(const FormatString (&),const std::string &,const uint32_t &,const uint32_t &)' being compiled
5>        with
5>        [
5>            FormatString=char [31]
5>        ]
5>E:\Syndra\Syndra\vendor\spdlog\include\spdlog\fmt\bundled\format.h(3509,18): error C2672: 'fmt::v7::detail::vformat_to': no matching overloaded function found
5>E:\Syndra\Syndra\vendor\spdlog\include\spdlog\fmt\bundled\format.h(3506,1): error C2780: 'basic_format_context<std::back_insert_iterator<fmt::v7::detail::buffer<T>>,Char>::iterator fmt::v7::detail::vformat_to(fmt::v7::detail::buffer<T> &,fmt::v7::basic_string_view<Char>,fmt::v7::basic_format_args<fmt::v7::basic_format_context<std::back_insert_iterator<fmt::v7::detail::buffer<type_identity<T>::type>>,type_identity<T>::type>>)': expects 3 arguments - 2 provided
5>E:\Syndra\Syndra\vendor\spdlog\include\spdlog\fmt\bundled\core.h(1775): message : see declaration of 'fmt::v7::detail::vformat_to'
5>stb_image.cpp
5>Generating Code...
5>Done building project "Syndra.vcxproj" -- FAILED.
6>------ Build started: Project: Syndra-Editor, Configuration: Debug x64 ------
6>LINK : fatal error LNK1104: cannot open file 'E:\Syndra\bin\Debug-windows-x86_64\Syndra\Syndra.lib'
6>Done building project "Syndra-Editor.vcxproj" -- FAILED.
========== Build: 4 succeeded, 2 failed, 0 up-to-date, 0 skipped ==========`

**Comment by sambsp** [comment]
@ErfanMo77 ,

After modified the code in format.h, Line 3510 to:

`fmt::v7::make_format_args<context>(args...));`

compile errors disappeared.

And left these errors:

![image](https://user-images.githubusercontent.com/4620696/147813888-8f187236-1e36-46ef-96eb-c7a34d2a08d1.png)

all these errors because shaderc_sharedd.lib not exist on the config path. 

So I search the installed VulkanSDK (by the script), but there is sharerc_shared.lib. No shaderc_sharedd.lib!

Output details:

Build started...
1>------ Build started: Project: Syndra, Configuration: Debug x64 ------
1>lpch.cpp
1>Application.cpp
1>Layer.cpp
1>LayerStack.cpp
1>Log.cpp
1>Window.cpp
1>ImGuiBuild.cpp
1>ImGuiLayer.cpp
1>Buffer.cpp
1>Environment.cpp
1>E:\Syndra\Syndra\src\Engine\Renderer\Environment.cpp(159,26): warning C4244: 'initializing': conversion from 'double' to 'unsigned int', possible loss of data
1>E:\Syndra\Syndra\src\Engine\Renderer\Environment.cpp(160,27): warning C4244: 'initializing': conversion from 'double' to 'unsigned int', possible loss of data
1>FrameBuffer.cpp
1>LightManager.cpp
1>Material.cpp
1>Mesh.cpp
1>E:\Syndra\Syndra\src\Engine\Renderer\Mesh.cpp(18,95): warning C4267: 'argument': conversion from 'size_t' to 'uint32_t', possible loss of data
1>E:\Syndra\Syndra\src\Engine\Renderer\Mesh.cpp(19,66): warning C4267: 'argument': conversion from 'size_t' to 'uint32_t', possible loss of data
1>Model.cpp
1>OrthographicCamera.cpp
1>PerspectiveCamera.cpp
1>E:\Syndra\Syndra\src\Engine\Renderer\PerspectiveCamera.cpp(121,31): warning C4244: '=': conversion from 'unsigned int' to 'float', possible loss of data
1>E:\Syndra\Syndra\src\Engine\Renderer\PerspectiveCamera.cpp(122,33): warning C4244: '=': conversion from 'unsigned int' to 'float', possible loss of data
1>RenderCommand.cpp
1>RenderPass.cpp
1>Renderer.cpp
1>RendererAPI.cpp
1>Generating Code...
1>Compiling...
1>SceneRenderer.cpp
1>E:\Syndra\Syndra\src\Engine\Renderer\SceneRenderer.cpp(39,51): warning C4267: 'argument': conversion from 'size_t' to 'uint32_t', possible loss of data
1>E:\Syndra\Syndra\src\Engine\Renderer\SceneRenderer.cpp(331,61): warning C4244: 'argument': conversion from 'float' to 'int', possible loss of data
1>E:\Syndra\Syndra\src\Engine\Renderer\SceneRenderer.cpp(332,71): warning C4244: 'argument': conversion from 'float' to 'int', possible loss of data
1>E:\Syndra\Syndra\src\Engine\Renderer\SceneRenderer.cpp(430,73): warning C4312: 'type cast': conversion from 'uint32_t' to 'ImTextureID' of greater size
1>E:\Syndra\Syndra\src\Engine\Renderer\SceneRenderer.cpp(438,73): warning C4312: 'type cast': conversion from 'uint32_t' to 'ImTextureID' of greater size
1>E:\Syndra\Syndra\src\Engine\Renderer\SceneRenderer.cpp(446,73): warning C4312: 'type cast': conversion from 'uint32_t' to 'ImTextureID' of greater size
1>E:\Syndra\Syndra\src\Engine\Renderer\SceneRenderer.cpp(454,73): warning C4312: 'type cast': conversion from 'uint32_t' to 'ImTextureID' of greater size
1>E:\Syndra\Syndra\src\Engine\Renderer\SceneRenderer.cpp(538,75): warning C4312: 'type cast': conversion from 'uint32_t' to 'ImTextureID' of greater size
1>Shader.cpp
1>Texture.cpp
1>UniformBuffer.cpp
1>VertexArray.cpp
1>Components.cpp
1>Entity.cpp
1>Light.cpp
1>Scene.cpp
1>E:\Syndra\Syndra\src\Engine\Scene\Scene.cpp(155,36): warning C4244: 'argument': conversion from 'uint32_t' to 'float', possible loss of data
1>E:\Syndra\Syndra\src\Engine\Scene\Scene.cpp(155,29): warning C4244: 'argument': conversion from 'uint32_t' to 'float', possible loss of data
1>SceneCamera.cpp
1>SceneSerializer.cpp
1>Math.cpp
1>E:\Syndra\Syndra\src\Engine\Utils\Math.cpp(37,16): warning C4101: 'Pdum3': unreferenced local variable
1>OpenGLBuffer.cpp
1>OpenGLContext.cpp
1>OpenGLFrameBuffer.cpp
1>E:\Syndra\Syndra\src\Platform\OpenGL\OpenGLFrameBuffer.cpp(129,72): warning C4267: 'argument': conversion from 'size_t' to 'GLsizei', possible loss of data
1>E:\Syndra\Syndra\src\Platform\OpenGL\OpenGLFrameBuffer.cpp(138,73): warning C4267: 'argument': conversion from 'size_t' to 'GLsizei', possible loss of data
1>E:\Syndra\Syndra\src\Platform\OpenGL\OpenGLFrameBuffer.cpp(153,84): warning C4267: 'argument': conversion from 'size_t' to 'uint32_t', possible loss of data
1>E:\Syndra\Syndra\src\Platform\OpenGL\OpenGLFrameBuffer.cpp(161,140): warning C4267: 'argument': conversion from 'size_t' to 'int', possible loss of data
1>E:\Syndra\Syndra\src\Platform\OpenGL\OpenGLFrameBuffer.cpp(164,141): warning C4267: 'argument': conversion from 'size_t' to 'int', possible loss of data
1>E:\Syndra\Syndra\src\Platform\OpenGL\OpenGLFrameBuffer.cpp(167,146): warning C4267: 'argument': conversion from 'size_t' to 'int', possible loss of data
1>E:\Syndra\Syndra\src\Platform\OpenGL\OpenGLFrameBuffer.cpp(208,52): warning C4267: 'argument': conversion from 'size_t' to 'GLsizei', possible loss of data
1>OpenGLRendererAPI.cpp
1>OpenGLShader.cpp
1>E:\Syndra\Syndra\src\Platform\OpenGL\OpenGLShader.cpp(262,71): warning C4267: 'initializing': conversion from 'size_t' to 'uint32_t', possible loss of data
1>E:\Syndra\Syndra\src\Platform\OpenGL\OpenGLShader.cpp(264,52): warning C4267: 'initializing': conversion from 'size_t' to 'int', possible loss of data
1>E:\Syndra\Syndra\src\Platform\OpenGL\OpenGLShader.cpp(299,71): warning C4267: 'initializing': conversion from 'size_t' to 'uint32_t', possible loss of data
1>E:\Syndra\Syndra\src\Platform\OpenGL\OpenGLShader.cpp(301,52): warning C4267: 'initializing': conversion from 'size_t' to 'int', possible loss of data
1>OpenGLTexture1D.cpp
1>OpenGLTexture2D.cpp
1>OpenGLUniformBuffer.cpp
1>Generating Code...
1>Compiling...
1>OpenGLVertexArray.cpp
1>WindowsInput.cpp
1>WindowsUtils.cpp
1>WindowsWindow.cpp
1>stb_image.cpp
1>Generating Code...
1>ImGuizmo.cpp
1>E:\Syndra\Syndra\vendor\ImGuizmo\ImGuizmo.cpp(1207,37): warning C4018: '<': signed/unsigned mismatch
1>LINK : fatal error LNK1181: cannot open input file 'vendor\VulkanSDK\Lib\shaderc_sharedd.lib'
1>Done building project "Syndra.vcxproj" -- FAILED.
2>------ Build started: Project: Syndra-Editor, Configuration: Debug x64 ------
3>------ Build started: Project: Sandbox, Configuration: Debug x64 ------
3>SandboxApp.cpp
2>EditorLayer.cpp
2>E:\Syndra\Syndra-Editor\src\EditorLayer.cpp(341,6): warning C4312: 'type cast': conversion from 'uint32_t' to 'ImTextureID' of greater size
2>E:\Syndra\Syndra-Editor\src\EditorLayer.cpp(353,6): warning C4312: 'type cast': conversion from 'uint32_t' to 'ImTextureID' of greater size
2>E:\Syndra\Syndra-Editor\src\EditorLayer.cpp(366,6): warning C4312: 'type cast': conversion from 'uint32_t' to 'ImTextureID' of greater size
2>E:\Syndra\Syndra-Editor\src\EditorLayer.cpp(374,6): warning C4312: 'type cast': conversion from 'uint32_t' to 'ImTextureID' of greater size
2>E:\Syndra\Syndra-Editor\src\EditorLayer.cpp(382,6): warning C4312: 'type cast': conversion from 'uint32_t' to 'ImTextureID' of greater size
3>LINK : fatal error LNK1104: cannot open file 'E:\Syndra\bin\Debug-windows-x86_64\Syndra\Syndra.lib'
3>Done building project "Sandbox.vcxproj" -- FAILED.
2>SyndraEditorApp.cpp
2>CameraPanel.cpp
2>ContentBrowser.cpp
2>E:\Syndra\Syndra-Editor\src\UI\Panels\ContentBrowser.cpp(42,8): warning C4312: 'type cast': conversion from 'uint32_t' to 'ImTextureID' of greater size
2>LightPanel.cpp
2>E:\Syndra\Syndra-Editor\src\UI\Panels\LightPanel.cpp(80,59): warning C4305: 'argument': truncation from 'double' to 'float'
2>MaterialPanel.cpp
2>E:\Syndra\Syndra-Editor\src\UI\Panels\MaterialPanel.cpp(11,61): warning C4312: 'type cast': conversion from 'uint32_t' to 'ImTextureID' of greater size
2>E:\Syndra\Syndra-Editor\src\UI\Panels\MaterialPanel.cpp(56,74): warning C4312: 'reinterpret_cast': conversion from 'uint32_t' to 'void *' of greater size
2>E:\Syndra\Syndra-Editor\src\UI\Panels\MaterialPanel.cpp(60,68): warning C4312: 'reinterpret_cast': conversion from 'uint32_t' to 'void *' of greater size
2>MeshPanel.cpp
2>ScenePanel.cpp
2>Generating Code...
2>LINK : fatal error LNK1104: cannot open file 'E:\Syndra\bin\Debug-windows-x86_64\Syndra\Syndra.lib'
2>Done building project "Syndra-Editor.vcxproj" -- FAILED.
========== Build: 0 succeeded, 3 failed, 4 up-to-date, 0 skipped ==========

**Comment by ErfanMo77** [comment]
Thank you for fixing that problem! would you mind making a pull request?

And about that Vulkan problem, did you run generateProjects.bat again? it copies necessary .lib files into the bin directory.

**Comment by sambsp** [comment]
I think I cannot make the pull request since the format.h is a vendor file of your submodule. I searched the same error and the this error appears before but spdlog seems fix this issue before. So maybe it's a include order problem, but I don't know how to solve it, sorry.

**Comment by ErfanMo77** [comment]
Yeah, you are right. I'll work on it. Thanks!

**Comment by ErfanMo77** [comment]
Updated spdlog to the latest commit. log.cpp was also updated. I think it's fixed now!
